<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>2.0.0</Version>
        <TargetFramework>net6.0</TargetFramework>
        <LangVersion>Latest</LangVersion>
        <GamePath>C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley</GamePath>
        <GameModsPath>$(GamePath)\ModsMinimal</GameModsPath>
        <EnableModDeploy>true</EnableModDeploy>
        <EnableModZip>true</EnableModZip>
        <ModFolderName>CrossModCompatibilityTools</ModFolderName>
        <Title>Cross-Mod Compatibility Tools</Title>
        <Authors>Spiderbuttons</Authors>
        <PackageId>CrossModCompatibilityTools</PackageId>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <OutputPath>bin\Debug</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.2.1">
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Pintail" Version="2.6.1" PrivateAssets="False" />
        <Publicize Include="StardewModdingAPI" />
        <Reference Include="Newtonsoft.Json" Private="False">
            <HintPath>$(GamePath)\smapi-internal\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1"/>
    </ItemGroup>
</Project>